# Device to monitor - will be overridden by systemd service
device_name = "AT Translated Set 2 keyboard"

# Left Alt → Left Super
[[remap]]
input = ["KEY_LEFTALT"]
output = ["KEY_LEFTMETA"]

# Caps Lock → Ctrl when held, Escape when tapped
[[dual_role]]
input = "KEY_CAPSLOCK"
hold = ["KEY_LEFTCTRL"]
tap = ["KEY_ESC"]
# Timeout in milliseconds for distinguishing tap from hold
tap_hold_interval = 200